config/routes.rb
Rails.application.routes.draw do
  # root to: "islands#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "islands#index"
  devise_for :users

  resources :islands do
    resources :bookings, only: [:new, :create]
  end

  resource :users do
    resources :bookings, only: [:index]
  end

  resources :bookings, only: [:show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :island
  validates :check_in_date, :check_out_date, presence: true, availability: true

  validate :check_out_after_check_in

  private

  def check_out_after_check_in
    return if check_out_date.blank? || check_in_date.blank?

    if check_out_date < check_in_date
      errors.add(:check_out_date, "must be after the check-in date")
    end
  end

end

app/models/island.rb
class Island < ApplicationRecord
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  validates :name, :capacity, :description, :location, :price, presence: true
  validates :price, comparison: { greater_than: 0 }

  include PgSearch::Model
  pg_search_scope :search_by_parameters,
    against: [ :name, :location, :description],
    using: {
      tsearch: { prefix: true } # <-- now `quiet will return something!
    }

  def unavailable_dates
    bookings.pluck(:check_in_date, :check_out_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :islands, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @island = Island.find(params[:island_id])
    @new = Booking.new()
  end

  def index
    @user = current_user
    @bookings = Booking.where(user_id: @user.id)
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    booking = Booking.new(booking_params)
    booking.island = Island.find(params[:island_id])
    booking.total_price = (booking.check_out_date - booking.check_in_date) * booking.island.price
    booking.user = current_user
    if booking.save
      # flash.now[:notice] = 'Booking done'
      redirect_to booking_path(booking)
    else
      flash.now[:alert] = 'Booking not valid'
      # redirect_to island_path(Island.find(params[:island_id]))
      # redirect_to new_user_session_path
    end
  end

  def edit
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to users_bookings_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:check_in_date, :check_out_date)
  end
end

app/controllers/islands_controller.rb
class IslandsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      @islands = Island.search_by_parameters(params[:query])
    else
      @islands = Island.all
    end

    # @markers = @islands.geocoded.map do |island|
    #   {
    #     lat: island.latitude,
    #     lng: island.longitude,
    #     # infoWindow: render_to_string(partial: "info_window", locals: { island: island })
    #   }
    # end
  end

  def new
    @island = Island.new
  end

  def create
    @island = Island.new(island_params)
    @island.user_id = current_user.id
    if @island.save
      redirect_to island_path(@island)
    else
      render :new
    end
  end

  def edit
    @island = Island.find(params[:id])
  end

  def show
    @island = Island.find(params[:id])
    @markers = [{
        lat: @island.latitude,
        lng: @island.longitude
      }]
  end

  def update
    @island = Island.find(params[:id])
    @island.update(island_params)
    redirect_to island_path(@island)
  end

  private

  def island_params
    params.required(:island).permit(:name, :capacity, :description, :price, :location, :availability, :photo)
  end
end

# create migration adding "photo" to island table - DONE
# db:migrate - DONE
# complete new/.create/edit/show method - DONE
# upload function + install gem to upload photo to cloudinary
# set up views/islands/

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<h1>Your booking history</h1>
<p>Hello <%= @user.first_name %>, these are the islands you've booked</p>

<div class="row">
  <% if @bookings.empty? %>
    <p>You have no current bookings</p>
  <% else %>
    <% @bookings.each do |booking| %>
      <div class="col-lg-4 mb-2">
        <%# MAYBE INSERT IMAGE OF ISLAND HERE? %>
        <div class="card-body border p-3 bg-white border-radius: 2px">
          <h5 class="card-title"><%= booking.island.name %></h5>
          <p class="card-text">From <%= booking.check_in_date.strftime("%d/%m/%Y") %> until <%= booking.check_out_date.strftime("%d/%m/%Y") %></p>
          <p class="card-text">Booking created on <%= booking.created_at.strftime("%d/%m/%Y") %></p>
          <p class="card-text">Total price: <%= number_to_currency(booking.total_price, unit: "USD") %></p>
          <%= link_to "Cancel booking", booking_path(booking),
                data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to cancel this booking?" },
                class: "btn btn-warning" %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <h1>Your booking is confirmed! 🎉 </h1>
        <div class="card_booking">
          <p>Island <%= @booking.island.name %> is booked by <%= @booking.user.first_name %></p>
          <p>Total price: $<%= @booking.total_price %></p>
          <p><%= link_to "See all my bookings", users_bookings_path, class: "btn btn-primary" %></p>
      </div>
</div>

app/views/islands/_card.html.erb
<div class="card" style="width: 280px; height: 400px;">
  <div class="w-100 h-100">
    <div class="card-img-top position-relative">
      <% if island.photo.attached? %>
      <%= cl_image_tag island.photo.key, height: 200, crop: :fill %>
      <% end %>
      <%# <div class="bookmark">Bookmark</div> %>
    </div>
    <div class="m-4">
      <div class="d-flex justify-content-between align-items-center mb-2">
        <div class="location">
          <%= island.location %>
        </div>
        <%# <span class="rating">Rating</span> %>
      </div>
      <h5 class="card-title mb-2 h-25"><%= island.name %></h5>
      <%# <% if island.availability %>
        <p class="card-text mb-2">Available</p>
      <%# <% else %>
        <%# <p class="card-text mb-2">Unavailable</p> %>
      <%# <% end %>
      <h6 class="card-subtitle mb-0 font-weight-bold">$<%= island.price %> AUD / day</h6>
      <%= link_to "Book now", island_path(island.id), class:"btn btn-primary d-block", style: "margin: 10px;"%>
    </div>
  </div>
</div>

app/views/islands/_form.html.erb
<%= simple_form_for @island do |f| %>
  <%= f.input :name %>
  <%= f.input :location %>
  <%= f.input :description %>
  <%= f.input :capacity %>
  <%= f.input :price %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Add island", class: "btn btn-primary" %>
<% end %>

app/views/islands/edit.html.erb
<h1>Islands#edit</h1>

<%= render "form", island: @island %>

app/views/islands/index.html.erb
<h1 style="margin-bottom: 30px; margin-top: 40px; text-align: center;">Book your next island getaway</h1>

<div class="row">
  <% @islands.each do |island| %>
    <div  class="d-flex col-xl-3 col-lg-4 col-md-6 mb-4">
      <!-- Repeat the below column code for each listing -->
      <%= render 'card', island: island %>
      <!-- End of repeated column code -->
    </div>
  <% end %>
</div>

app/views/islands/new.html.erb
<div class="container">
  <h1>Add your island</h1>
  <p>Please add your details in below:</p>

  <%= render "form", island: @island %>
</div>

app/views/islands/show.html.erb
<div class="container">
  <h1>Details about this beautiful island</h1>
  <p><strong>Location:</strong> <%= @island.location %> | <strong>Host:</strong> <%= @island.user.first_name %> Developer</p>
  <%= cl_image_tag @island.photo.key, height: 250, crop: :fill %>
  <% if @island.photo.attached? %>
  <% end %>

  <h4>Private island for rent by <%= @island.user.first_name %> </h4>
  <%# Still need to add user AVATAR (CREATE CSS AVATAR COMPONENT) %>

  <div class="island_detail">
    <div class="island_description">
      <%= @island.description %></p>
      <p><strong>Price per day:</strong> $<%= @island.price %></p>
      <p><strong>Capacity (# of guests):</strong> <%= @island.capacity %> persons</p>
    </div>

    <div class="booking_form">
      <h3>Book this island</h3>
      <div id='island-booking-dates' data-unavailable="<%= @island.unavailable_dates.to_json %>">
      <p>
        <%= simple_form_for [@island, @booking = Booking.new], data: { controller: 'flatpickr', flatpickr_day_rate_value: @island.price } do |f| %>
          <%= f.input :check_in_date, as: :string, input_html: { data: { flatpickr_target: "checkInDate" } } %>
          <%= f.input :check_out_date, as: :string, input_html: { data: { flatpickr_target: "checkOutDate" }, id: "checkOutDate" } %>
          <div class="total_price">Total Price: $<span data-flatpickr-target="totalPrice"></span></div>
          <%= f.submit "Reserve", class: "btn btn-success" %>
        <% end %>
      </p>
      </div>
    </div>
  </div>

  <div data-controller="map"
        id='map'
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
        data-map-markers-value="<%= @markers.to_json %>"
        style='width: 100%; height: 400px;'></div>

  <div class="btn_view">
  <hr>
    <p><%= link_to "View all islands", islands_path, class: 'btn btn-primary' %></p>
  </div>
</div>

<%# <%= link_to "Edit your listing", island_path, class: 'btn btn-warning' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAnIsland</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.css' rel='stylesheet' />
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div style="min-height: 100vh">
    <%= render '/components/navbar' %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </div>
  <%= render 'components/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="row">
      <!-- Repeat the below column code for each listing -->
    <div class="col-lg-3 col-md-6 mb-4">
      <div class="card h-100">
        <div class="card-img-top position-relative">
          <div class="bookmark">Bookmark</div>
        </div>
        <div class="card-body">
          <div class="d-flex justify-content-between align-items-center mb-2">
            <span class="location">Location</span>
            <span class="rating">Rating</span>
          </div>
          <h5 class="card-title mb-2">Name</h5>
          <p class="card-text mb-2">Availability</p>
          <h6 class="card-subtitle mb-0 font-weight-bold">$Price</h6>
        </div>
      </div>
    </div>
      <!-- End of repeated column code -->
</div>